export default {
  SETTING_GET_REQUESTED: "SETTING_GET_REQUESTED",
  SETTING_GET_SUCCEEDED: "SETTING_GET_SUCCEEDED",
  SETTING_GET_FAILED: "SETTING_GET_FAILED",

  SETTING_POST_REQUESTED: "SETTING_POST_REQUESTED",
  SETTING_POST_SUCCEEDED: "SETTING_POST_SUCCEEDED",
  SETTING_POST_FAILED: "SETTING_POST_FAILED"
};
